#!/usr/bin/env lua
-- -*- lua -*-

local umf=require("umf")
local utils=require("utils")

NumberSpec=umf.NumberSpec
StringSpec=umf.StringSpec
BoolSpec=umf.BoolSpec
FunctionSpec=umf.FunctionSpec
EnumSpec=umf.EnumSpec
TableSpec=umf.TableSpec
ClassSpec=umf.ClassSpec
ObjectSpec=umf.ObjectSpec

function help()
   print( [=[
umfcheck v0.1
validate uMF models.
  Usage:
     umfcheck OPTIONS <modelfile> <specfile>
  Options:
	-q    quiet, no output
	-h    print help
	     ]=] )
end

function check_file(f, name)
   if not utils.file_exists(f) then
      print("error: no "..name.." "..specfile)
      os.exit(1)
   end
   return f
end

local argtab=utils.proc_args(arg)

if #arg<2 or argtab['-h'] then help(); os.exit(1); end

local specfile = check_file(arg[#arg])
local modelfile = check_file(arg[#arg-1])

local spec = dofile(specfile)
local model = dofile(modelfile)

if not spec then print("err: no spec could be loaded from file "..specfile) end
if not model then print("err: no model could be loaded from file "..modelfile) end

if umf.check(model, spec, (not argtab['-q']))~=0 then os.exit(0)
else os.exit(2) end
